//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BunAndBagel.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public Nullable<int> Id_Order { get; set; }
        public Nullable<int> Id_Product { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ProductBunAndBagel ProductBunAndBagel { get; set; }
    }
}
