//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BunAndBagel.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BunAndBagelEntities : DbContext
    {
        private static BunAndBagelEntities _context;
        public BunAndBagelEntities()
            : base("name=BunAndBagelEntities")
        {
        }

		public static BunAndBagelEntities GetContext()
		{
			if (_context == null)
				_context = new BunAndBagelEntities();
			return _context;
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Balance> Balance { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Cook> Cook { get; set; }
        public virtual DbSet<Filling> Filling { get; set; }
        public virtual DbSet<KindBunAndBagel> KindBunAndBagel { get; set; }
        public virtual DbSet<KindDough> KindDough { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderingProducts> OrderingProducts { get; set; }
        public virtual DbSet<ProductBunAndBagel> ProductBunAndBagel { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<StatusOrder> StatusOrder { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
