//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BunAndBagel.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderingProducts
    {
        public int Id { get; set; }
        public int IdOrder { get; set; }
        public int IdUser { get; set; }
        public int IdProduct { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ProductBunAndBagel ProductBunAndBagel { get; set; }
        public virtual User User { get; set; }
    }
}
