//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BunAndBagel.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBunAndBagel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductBunAndBagel()
        {
            this.Cart = new HashSet<Cart>();
            this.OrderingProducts = new HashSet<OrderingProducts>();
        }
    
        public int Id { get; set; }
        public int Id_Category { get; set; }
        public int Id_Kind { get; set; }
        public int Id_Dough { get; set; }
        public int Id_Filling { get; set; }
        public int Id_Cook { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int Weight { get; set; }
        public int Quantity { get; set; }
        public string Photo { get; set; }
        public string Desciption { get; set; }

		public string CurrentPhoto
		{
			get
			{
				if (string.IsNullOrEmpty(Photo) || String.IsNullOrWhiteSpace(Photo))
				{
					return "/Picture/Logotip.png";
				}
				else
				{
					return "/Picture/" + Photo;
				}
			}
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual Category Category { get; set; }
        public virtual Cook Cook { get; set; }
        public virtual Filling Filling { get; set; }
        public virtual KindBunAndBagel KindBunAndBagel { get; set; }
        public virtual KindDough KindDough { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderingProducts> OrderingProducts { get; set; }
    }
}
